### ISSUE TITLE
ActiveMQ接收消息报未设置响应目标

### ISSUE THREAD

**Issue by teclan** [teclan/teclan-SpringBoot#2]
# 操作

启动程序，访问 `http://localhost:8080/send/queue1`

# 错误日志

```
接收到ActiveMQ（queue1）消息：{"name":"teclan"}
2019-01-04 15:46:47.956 ERROR 9620 --- [enerContainer-1] t.s.config.ActiveMQErrorHandler          : Failed to send reply with payload [true]; nested exception is javax.jms.InvalidDestinationException: Cannot determine response destination: Request message does not contain reply-to destination, and no default response destination set.
org.springframework.jms.listener.adapter.ReplyFailureException: Failed to send reply with payload [true]; nested exception is javax.jms.InvalidDestinationException: Cannot determine response destination: Request message does not contain reply-to destination, and no default response destination set.
	at org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener.handleResult(AbstractAdaptableMessageListener.java:285) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:79) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: javax.jms.InvalidDestinationException: Cannot determine response destination: Request message does not contain reply-to destination, and no default response destination set.
	at org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener.getResponseDestination(AbstractAdaptableMessageListener.java:393) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener.getResponseDestination(AbstractAdaptableMessageListener.java:366) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener.handleResult(AbstractAdaptableMessageListener.java:281) ~[spring-jms-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 10 common frames omitted

2019-01-04 15:46:47.979  INFO 9620 --- [nio-8080-exec-2] t.s.avtivemq.Queue1SenderServer          : 

```

**Comment by teclan** [comment]
# 问题来源

```
   /**
     * 接收消息
     *
     * @param message
     */
    @JmsListener(destination = "queue1", containerFactory = "jmsListenerContainerQueue")
    @Override
    public boolean receiveQueueMsg(String message) throws UnImplementException {
        try {
            return receiveQueueMsg(getQueueName(), message);
        } catch (Exception e) {
            LOGGER.error(e.getMessage(), e);
        }
        return false;
    }
```

使用 `JmsListener`注解的方法不允许返回值，将返回值设置为`void`即可，如果需要确认消息是否处理成功，可自定义采用回调的形式予以处理，即将代码逻辑简单改成以下即可：

```
/**
     * 接收消息
     *
     * @param message
     */
    @JmsListener(destination = "queue1", containerFactory = "jmsListenerContainerQueue")
    @Override
    public void receiveQueueMsg(String message) throws UnImplementException {
        try {
             receiveQueueMsg(getQueueName(), message);
        } catch (Exception e) {
            LOGGER.error(e.getMessage(), e);
        }
    }

```
